feat: create delegate profile @bruno
unik-name/uns-delegates-website pull request #31
Opened 2021-06-21 18:58 UTC by brunosez

2021-06-22 07:25 UTC, dlecan requested changes
Thank you for your contribution!

Can you please review your README contribution?
It doesn't respect the expected format.

Here is a raw example:
https://github.com/unik-name/uns-delegates-website/edit/master/docs/delegates/110688c7e2b4ce9f369aade0e5e6d8076a5beb28066d473bcaa4f0ddb124803c/README.md

You should respect YAML and Mardown formats

2021-06-22 07:26 UTC, dlecan commented on docs/delegates/44908e9ac567d211643bffc82710adf4b0172f13bf4a6bcecc794f156458fc81/README.md
> +  - **46.226.107.88  version 5.6.2**, was OVH hosted but fire in Strasbourg's DC drives me to Gandi hosting :-)
The version will be automatically extracted by a Bot later

2021-06-22 07:27 UTC, dlecan commented on docs/delegates/44908e9ac567d211643bffc82710adf4b0172f13bf4a6bcecc794f156458fc81/README.md
> +  - **46.226.107.88  version 5.6.2**, was OVH hosted but fire in Strasbourg's DC drives me to Gandi hosting :-)
> was OVH hosted but fire in Strasbourg's DC drives me to Gandi hosting :-)

Explain this in the `Summary`, it's a quite funny fact :smile:

2021-06-22 07:27 UTC, dlecan commented on docs/delegates/44908e9ac567d211643bffc82710adf4b0172f13bf4a6bcecc794f156458fc81/README.md
> +website: TBD https://example.com
If no website, remove it

2021-06-23 15:54 UTC, dlecan requested changes
Much better :clap: 

Do you know to can preview your page?
:point_right: https://deploy-preview-31--uns-delegates.netlify.app/delegates/44908e9ac567d211643bffc82710adf4b0172f13bf4a6bcecc794f156458fc81/

Still to fix:
- website can't be loaded
- several unclickable links

2021-06-23 16:22 UTC, brunosez commented
Thanks for the preview site.

I have fixed some blank

is it OK now ?

Le mer. 23 juin 2021 à 17:54, Damien Lecan ***@***.***> a
écrit :

> ***@***.**** requested changes on this pull request.
>
> Much better 👏
>
> Do you know to can preview your page?
> 👉
> https://deploy-preview-31--uns-delegates.netlify.app/delegates/44908e9ac567d211643bffc82710adf4b0172f13bf4a6bcecc794f156458fc81/
>
> Still to fix:
>
>    - website can't be loaded
>    - several unclickable links
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/unik-name/uns-delegates-website/pull/31#pullrequestreview-690856806>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABK32YZYFSKW32W37RZ4FNLTUH7SLANCNFSM47CEUKYQ>
> .
>

2021-06-28 07:59 UTC, dlecan approved these changes

2021-06-28 08:00 UTC, dlecan commented
Great, thank you!
Can you sign your commits, please? 
https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/signing-commits

2021-06-28 12:07 UTC, brunosez commented
Hi Damien ,
i've set up the PGP key, is it ok on your side ?
Rgds , have a nice week :-)

2021-06-28 14:21 UTC, dlecan commented
Great, your new commits are signed!
You can sign the previous ones on the branch?

Thank you

2021-06-29 11:42 UTC, merged